// src/reducers/AppraisalSliceConstants.ts
import { IncomingAppraisalData, IncomingKRAItem } from '../types/AppraisalTypes'

export const initialAppraisalKra: IncomingKRAItem = {
  id: -1,
  name: '',
  description: null,
  designationKraPercentage: 0,
  kpis: [],
  count: 0,
}

export const initialAppraisalData: IncomingAppraisalData = {
  id: -1,
  appraisalCycle: {
    id: -1,
    name: '',
    description: '',
    toDate: '',
    fromDate: '',
    active: false,
    appraisalType: '',
    appraisalDuration: '',
    level: -1,
    cycleStartedFlag: false,
    appraisalStartDate: '',
    appraisalEndDate: '',
    servicePeriod: -1,
  },
  kra: [],
  employee: {
    id: -1,
    designation: '',
    acknowledged: null,
    fullName: '',
    profilePicPath: '',
    thumbPicture: '',
    departmentName: '',
    emailId: '',
    empManager: '',
  },
  formStatus: 'SAVE',
  formStatusvalue: 0,
  formRating: null,
  appraisalFormStatus: null,
  adjustedAvgRating: null,
  finalFeedback: null,
  avgRatingsDtos: [],
  overallAvgRating: '',
  overallAvgRatingName: null,
  finalRating: null,
  finalRatingName: null,
  discussionOn: null,
  discussionSummary: null,
  openForDiscussionFlag: null,
  iAgreeFlag: null,
  closedSummary: null,
  closedOn: null,
  pendingWith: null,
  closedStatus: null,
  closedBy: null,
  empDepartmentName: null,
  empDesignationName: null,
  empAvgRating: null,
  empAvgRatingName: null,
  manager1Name: null,
  requestDiscussion: false,
}
